name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  steps:
    
    runs-on: ubuntu-latest
    
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_RIVER_046B2C410 }}
          ##repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          
          ###### End of Repository/Build Configurations ######

  
